version: '3.8'


services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    env_file:
      - .env
    depends_on: #El contenedor backend no se levantará hasta que el contenedor de postgres esté list
      - postgres
      - redis
      - mailpit
      - minio
    

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    ports:
      - "8025:8025"  # Web UI para ver correos
      - "1025:1025"  # Puerto SMTP
    env_file:
      - .env

  minio:
      container_name: minio
      image: minio/minio
      ports:
        - "9000:9000"   # API de MinIO
        - "9001:9001"   # Consola web
      command: server /data --console-address ":9001"
      environment: 
        MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}      
      volumes:
        - minio_data:/data
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - "8055:8055"  # Panel web de Directus
    environment:
      KEY: ${DIRECTUS_SECRET} # Puedes poner cualquier valor secreto
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin1234
      DB_CLIENT: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PUBLIC_URL: http://localhost:8055
      SECRET: ${DIRECTUS_SECRET}
    depends_on:
      - postgres
    volumes:
      - directus_data:/directus
volumes:
  postgres_data:
  minio_data:
  directus_data:

