version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=test
    depends_on: #El contenedor backend no se levantará hasta que el contenedor de postgres esté list
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"  # Web UI para ver correos
      - "1025:1025"  # Puerto SMTP

  minio:
      image: minio/minio
      container_name: minio
      ports:
        - "9000:9000"   # API de MinIO
        - "9001:9001"   # Consola web
      environment:
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: admin123
      command: server /data --console-address ":9001"
      volumes:
        - minio_data:/data
volumes:
  postgres_data:
  minio_data:

