version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
